### ISSUE TITLE
[invader] Create an invader bitmap class

### ISSUE THREAD

**Issue by SnowyMouse** [SnowyMouse/invader#125]
Invader can make bitmap tags with parameters not originally present in the original game.

Unfortunately this means stepping on the original Bungie definitions. This should be stored in a class.

**Comment by Kavawuvi** [comment]
extended_bitmap has been made. What needs to be added is a stubbed attribute to signal to the map compiler that data in the bitmap tag should be ignored. This feature will only be supported when building for MCC and shall error if building for any other target.

**Comment by Kavawuvi** [comment]
invader-bitmap should provide an option to Zstandard the processed pixel data. This is _technically_ redundant when the map can be Zstandard-compressed, but this can be used to cheat the 4 GiB map file limit while also keeping memory usage lower when the map is fully loaded.

That said, this will incur a slight latency for loading these bitmaps, but this can be handled through decompressing everything ahead of time on map load at the user's discretion.

It should also Zstandard the color plate data at all times. Deflate is technically inferior, here.

**Comment by Kavawuvi** [comment]
Color plate data is now Zstandard'd as of https://github.com/Kavawuvi/invader/commit/dee8ec28c5b4ab44e5796a1dd9a2342a2a64e981

**Comment by SnowyMouse** [comment]
Making custom tag classes is a bit out of scope for Invader now, so I'm going to close this.
