### ISSUE TITLE
[invader-extract] possible cache only data left in scenario tag after extraction

### ISSUE THREAD

**Issue by Vaporeon** [SnowyMouse/invader#128]
After doing a full extraction of the localised versions of Halo to do a comparison I noticed the scenario tags differ. After looking in a hex editior they seem to be offsets of some kind in the script data. These could possibly be cache only or leftover tool.exe garbage.

**Comment by SnowyMouse** [comment]
Invader now recompiles scripts on build, as syntax data in its entirety is completely regenerated on build time.

Therefore, this issue isn't a problem anymore, although it should _probably_ set the function indices later when these indices can be mapped out.
