### ISSUE TITLE
[invader] Create a new extended scenario tag class

### ISSUE THREAD

**Issue by Vaporeon** [SnowyMouse/invader#172]
We should create a new re-factored and extended scenario tag definition for native use with invader.
Firstly, we could take the opportunity to remove fields we have no use for, like the dead references and editor data.

We could also add new features, like having the globals be referenced by the scenario rather than hard-coded to a specific path.

We should also fix some issues with the original engine, one of these being that each AI conversation line variant should have a "variant number" value paired with the sound reference. This would be set by the user to the same value used in the intended biped tag. Adding this will remove the dependence on a gross hard-coded tag path matching hack tool.exe uses to calculate this value.

**Comment by Kavawuvi** [comment]
@everyone

**Comment by SnowyMouse** [comment]
No.

**Comment by Vaporeon** [comment]
No.
