### ISSUE TITLE
[invader-sound] conversions are not preserving all tag parameters. 

### ISSUE THREAD

**Issue by Apocalypse612** [SnowyMouse/invader#177]
Below I have included two sound files. One was an original, the other I converted through invader-sound. As you can see, this tool is stripping out a lot of the original tag params, including (but not limited to):

Randomization
	Gain Modifier: Being set to 1 instead of preserved.
	
When Scale is ZERO
	Skip Fraction Modifier: Zeroed out, instead of preserved.
	Gain Modifier: Zeroed out, instead of preserved.
	Pitch MOdifier: Zeroed out, instead of preserved.
	
When Scale is ONE
	Skip Fraction Modifier: Zeroed out, instead of preserved.
	Gain Modifier: Zeroed out, instead of preserved.
	Pitch MOdifier: Zeroed out, instead of preserved.
	
Pitch Control
	Natural Pitch: Zeroed out, instead of preserved.
	Bend Bound, Max: Zeroed out, instead of preserved.

- Unsure of any others that might be getting zeroed out, as this particular file is supposed to have a lot of zeroes in it already.

----

This is from my initial test of cor05b.sound from the a10 campaign map (xbox). 

[invader-soud sound tag data removal (bug).zip](https://github.com/Kavawuvi/invader/files/5099279/invader-soud.sound.tag.data.removal.bug.zip)

**Comment by Kavawuvi** [comment]
Sorry for not getting back to you on this soon. I'll be giving this a look!

My guess is it's creating a new sound tag and copying things in rather than editing the existing sound tag and copying things in.

**Comment by SnowyMouse** [comment]
So it seems I may have fixed this a while ago!

I gave it a look on the latest Invader and it seems to be preserving these values as expected. Can you verify this?

**Comment by SnowyMouse** [comment]
Closing this issue as it's been over a year and you have not responded, in which I'm fairly certain the issue was fixed.

If you find this message somewhere in the future and are _still_ experiencing the issue, feel free to reply.
