### ISSUE TITLE
[invader-build] Set the sequence bitmap count correctly when building sprites.

### ISSUE THREAD

**Issue by Vaporeon** [SnowyMouse/invader#184]
For whatever reason tool will zero the bitmap count in sequences when building sprite bitmaps into a map, `invader-build` should do this too. `invader-extract` should also undo this on extraction.

**Comment by SnowyMouse** [comment]
I though Invader did this already.

https://github.com/SnowyMouse/invader/commit/393ea25c4a40affd2483dcde7893bf5afd84292c (building) and https://github.com/SnowyMouse/invader/commit/fc3dc218c7f40ce3df32dd211a57e1a11d586f31 (extraction)

**Comment by SnowyMouse** [comment]
Fixed in beae705b86314088683ca16f2609aae9e999ee50

Turns out I only did the bitmap index, not the count.
