### ISSUE TITLE
[invader-build] Some values in sound tags are incorrectly defaulted.

### ISSUE THREAD

**Issue by Vaporeon** [SnowyMouse/invader#186]
Current behaviour is to set both  `zero_gain_modifier` and `one_gain_modifier` to `1` if both are `0`. This is incorrect, the set defaults are variable based on the configured sound class. Some examples are that `game event` will default them to `1, 1`, ambient nature will default to `0, 1`, and ambient machinery will default to `0.5, 0.5` respectively. Every possible class will need to be tested.

**Comment by SnowyMouse** [comment]
Oh wow. This will be fun!

**Comment by SnowyMouse** [comment]
Fixed in 0e73afaa34aeec5472fbf734523a97726ce6a2d2

Basically, some sound classes do NOT set the zero gain modifier to 0, only the one gain modifier.
