### ISSUE TITLE
invader-extract no works in others folders

### ISSUE THREAD

**Issue by PumbleCorp** [SnowyMouse/invader#188]
![image](https://user-images.githubusercontent.com/35852502/99114779-5cbfff80-25bf-11eb-9242-f7afd3de5ad9.png)

**Comment by SnowyMouse** [comment]
This is correct behavior, but I suppose I should better describe what the arguments do.

Basically, `-m` uses a maps folder to find your bitmaps.map, sounds.map, and loc.map (if applicable). The map does not need to be relative to this directory. By default, it will check the directory your map is in to do this.

The `<map>` argument is the path to your map. If your map is in the maps folder (as opposed to a different folder such as your downloads folder or your desktop), you do not need to specify `-m`.

**Comment by PumbleCorp** [comment]
The folder maps is inside of the folder where is Invader, in the first capture and the second capture the maps also stay here (same what in the first capture) in the folder root of halo custom edition (C:\Program Files (x86)\Microsoft Games\Halo Custom Edition\maps)

![image](https://user-images.githubusercontent.com/35852502/99202151-33000780-277c-11eb-9055-c1fd6b7a85ac.png)
![image](https://user-images.githubusercontent.com/35852502/99202720-0f3dc100-277e-11eb-868e-cd900710880b.png)

idk what happen here, Snowy.

**Comment by SnowyMouse** [comment]
Sorry for the long reply - been working on other projects simultaneously.

Anyway, my guess is it thinks you are not giving it the correct number of arguments. It looks like the quotation marks are a bit different in that screenshot than the last one you posted.
