### ISSUE TITLE
[invader-build] "map u(v) scale " does not get defaulted correctly on transparent shaders.

### ISSUE THREAD

**Issue by Vaporeon** [SnowyMouse/invader#192]
Current behaviour is to default to "1" if "0"

`tool.exe` behaviour is to default either `map u scale` or `map v scale` to the value of the other if that is set, otherwise if both are "0" it defaults both to "1".

Examples:
`map u scale 1.05, map v scale 0` would default to `map u scale 1.05, map v scale 1.05`
`map u scale 0, map v scale 1.05` would default to `map u scale 1.05, map v scale 1.05`
`map u scale 0, map v scale 0` would default to `map u scale 1, map v scale 1`

This applies to `shader_transparent_chicago`, `shader_transparent_chicago_extended` four stage and two stage, and `shader_transparent_generic`.

**Comment by SnowyMouse** [comment]
Fixed by 51726193b99de72fb90da6c83a193ec2e399fc3c
