### ISSUE TITLE
[invader-edit-qt] bitmap preview window can only be opened once per opening of a bitmap tag.

### ISSUE THREAD

**Issue by Vaporeon** [SnowyMouse/invader#202]
Open a bitmap tag and then open the preview, if you close the preview then it will not open again until you close and reload the tag.
This seems to be a regression.

**Comment by SnowyMouse** [comment]
Fixed in https://github.com/SnowyMouse/invader/commit/049867f12749a88cf4320643454884c3bef1f4e0
