### ISSUE TITLE
[invader-extract/invader-build] re-add support extracting and building MCC CEA BSP tags.

### ISSUE THREAD

**Issue by Vaporeon** [SnowyMouse/invader#208]
CEA stores BSP vertices in a different location for some reason, invader should support this so the tags can be read.

**Comment by SnowyMouse** [comment]
Added extraction in https://github.com/SnowyMouse/invader/commit/2848faf423f14af8e16cb4471c1dc9eee1981de7

**Comment by SnowyMouse** [comment]
This was completed a while ago. Closing issue now.
